### ISSUE TITLE
Resume option not available

### ISSUE THREAD

**Issue by rajatgoyal715** [rajatgoyal715/Puzzle15#37]
Whenever you start a new game, when no resume option is not available and then you go back to the previous screen, the resume option is not available.

![resume_error](https://user-images.githubusercontent.com/18263409/53695949-cdbd8480-3de7-11e9-9bc5-8bc893989e6c.gif)

**Comment by therealshabi** [comment]
## Suggestions

- When a user presses the back button, an alert should be given to `Go back to the Main Screen`, and subsequently `MainActivity` should be loaded from intent. In this solution, `onBackPressed` needs to be overridden. Additionally, finish the MainActivity when GameActivity is loaded using intent.
- Or, you can give the user a couple of options when he/she presses the back button:-
1. Start a new Game (Progress will be lost)
2. Go back to Main Screen (launch MainActivity from intent, as with the first case)
3. See Rules (Maybe user want to just check the rules, so we can quickly show them the rules then and there)
4. Quit and exit

**Comment by rish971** [comment]
> ## Suggestions
> * When a user presses the back button, an alert should be given to `Go back to the Main Screen`, and subsequently `MainActivity` should be loaded from intent. In this solution, `onBackPressed` needs to be overridden. Additionally, finish the MainActivity when GameActivity is loaded using intent.
> * Or, you can give the user a couple of options when he/she presses the back button:-
> 
> 1. Start a new Game (Progress will be lost)
> 2. Go back to Main Screen (launch MainActivity from intent, as with the first case)
> 3. See Rules (Maybe user want to just check the rules, so we can quickly show them the rules then and there)
> 4. Quit and exit

IMO second option i.e "pause menu" is better.
