### ISSUE TITLE
Create Github Pages

### ISSUE THREAD

**Issue by rajatgoyal715** [rajatgoyal715/Puzzle15#51]
We can create Github Pages for this project, which will be available on https://rajatgoyal715.github.io/Puzzle15

**Comment by therealshabi** [comment]
Do we really need to do that? I think a good neat Readme would be enough.
Moreover, this is not that big or unique a project to have a GitHub page. What do you think?

**Comment by rajatgoyal715** [comment]
@therealshabi Yeah, you are correct. But having one is not also bad, as it is just going to take two minutes.

**Comment by therealshabi** [comment]
Having a GitHub page is not bad, and even if it takes two minutes, in my opinion, you should devote that for some other more **important** issues, adding these unnecessary overheads might decrease the actual potential of the app. You have created Github pages before, so this is not even a new learning for you I'm sure?
